### ISSUE TITLE
Driver does not compile with Mbed OS 6

### ISSUE THREAD

**Issue by teetak01** [ARMmbed/mbed-os-atecc608a#15]
```
[Error] hal_mbed.cpp@57,5: 'wait_ms' was not declared in this scope; did you mean 'wait_ns'?
[ERROR] ./drivers/COMPONENT_ATECC608A/mbed-cryptoauthlib/source/hal_mbed.cpp: In function 'void atca_delay_ms(uint32_t)':

./drivers/COMPONENT_ATECC608A/mbed-cryptoauthlib/source/hal_mbed.cpp:57:5: error: 'wait_ms' was not declared in this scope; did you mean 'wait_ns'?

57 |     wait_ms(delay);
```

Tested with Device Management client example using the Secure Element configuration:

https://github.com/ARMmbed/mbed-cloud-client-example/blob/master/configs-psa/eth_v4_with_se_atmel.json and Mbed OS 6 beta

**Comment by 0xc0170** [comment]
Thanks for the report, wait_ms was deprecated long time ago and removed. `'ThisThread::sleep_for` should be used.

**Comment by Patater** [comment]
Fixed on 2020-03-11 (a long time ago) in https://github.com/ARMmbed/mbed-cryptoauthlib/commit/6d48daef3fba56ee0584fc7611b40776837dddfe
